use anyhow::{Error, Result};
use heapless::{String, Vec};
use serde::Deserialize;

/// # Parse Response ID
///
/// In order to know which kind of response we are dealing with, we need to parse the response ID.
///
/// ## Parameters
///
/// resp: The slice response to parse.
///
/// ## Examples
/// ```
/// use stratum_v1::client_resp::parse_response_id;
///
/// let resp = br#"{"id": 1, "result": [ [ ["mining.set_difficulty", "b4b6693b72a50c7116db18d6497cac52"], ["mining.notify", "ae6812eb4cd7735a302a8a9dd95cf71f"]], "08000002", 4], "error": null}"#;
/// assert_eq!(parse_response_id(resp).unwrap(), Some(1));
///
/// let resp = br#"{"error":null,"id":2,"result":[[["mining.notify","e26e1928"]],"e26e1928",4]}"#;
/// assert_eq!(parse_response_id(resp).unwrap(), Some(2));
///
/// let resp = br#"{ "id": null, "method": "mining.set_difficulty", "params": [2]}"#;
/// assert_eq!(parse_response_id(resp).unwrap(), None);
///
/// let resp = br#"{ "id": "ab", "method": "mining.set_difficulty", "params": [2]}"#;
/// assert!(parse_response_id(resp).is_err());
/// ```
pub fn parse_response_id(resp: &[u8]) -> Result<Option<u64>> {
    #[derive(Deserialize)]
    struct IdOnly {
        id: Option<u64>,
    }
    let id = serde_json_core::from_slice::<IdOnly>(resp)
        .map_err(Error::msg)?
        .0
        .id;
    match id {
        None => Ok(None),
        Some(id) => Ok(Some(id)),
    }
}

#[derive(Debug, Deserialize, PartialEq)]
pub struct ConfigureResp {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "version-rolling")]
    pub version_rolling: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "version-rolling.mask")]
    pub version_rolling_mask: Option<String<8>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "version-rolling.min-bit-count")]
    pub version_rolling_min_bit_count: Option<u8>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "minimum-difficulty")]
    pub minimum_difficulty: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "minimum-difficulty.value")]
    pub minimum_difficulty_value: Option<u32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "subscribe-extranonce")]
    pub subscribe_extranonce: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "info")]
    pub info: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "info.connection-url")]
    pub info_connection_url: Option<String<32>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "info.hw-version")]
    pub info_hw_version: Option<String<32>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "info.sw-version")]
    pub info_sw_version: Option<String<32>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "info.hw-id")]
    pub info_hw_id: Option<String<32>>,
}

/// # Parse Response Configure
///
/// Parses the response to the `configure` method.
///
/// ## Parameters
///
/// resp: The response slice to parse.
///
/// ## Examples
/// ```
/// use stratum_v1::client_resp::{ConfigureResp, parse_response_configure};
/// use heapless::String;
///
/// let resp = br#"{"error": null,"id": 1,"result": {"version-rolling": true,"version-rolling.mask": "18000000","minimum-difficulty": true}}"#;
/// assert_eq!(parse_response_configure(resp).unwrap(), ConfigureResp {
///     version_rolling: Some(true),
///     version_rolling_mask: Some(String::from("18000000")),
///     version_rolling_min_bit_count: None,
///     minimum_difficulty: Some(true),
///     minimum_difficulty_value: None,
///     subscribe_extranonce: None,
///     info: None,
///     info_connection_url: None,
///     info_hw_version: None,
///     info_sw_version: None,
///     info_hw_id: None
/// });
/// ```
pub fn parse_response_configure(resp: &[u8]) -> Result<ConfigureResp> {
    serde_json_core::from_slice::<json_rpc_types::Response<ConfigureResp, String<64>>>(resp)
        .map_err(Error::msg)?
        .0
        .payload
        .map_err(Error::msg)
}

#[derive(Debug, Deserialize, PartialEq)]
pub struct ConnectResp(
    // Subscriptions details - 2-tuple with name of subscribed notification and subscription ID. Teoretically it may be used for unsubscribing, but obviously miners won't use it.
    Vec<Vec<String<32>, 2>, 2>,
    // Extranonce1 - Hex-encoded, per-connection unique string which will be used for coinbase serialization later. Keep it safe!
    String<8>,
    // Extranonce2_size - Represents expected length of extranonce2 which will be generated by the miner.
    usize,
);

impl ConnectResp {
    pub fn subscriptions(&self) -> &Vec<Vec<String<32>, 2>, 2> {
        &self.0
    }

    pub fn extranonce1(&self) -> u32 {
        let v: Vec<u8, 4> = hex::decode_heapless(&self.1).expect("decode error");
        u32::from_be_bytes(v[0..4].try_into().unwrap())
    }

    pub fn extranonce2_size(&self) -> usize {
        self.2
    }
}

/// # Parse Response Connect
///
/// Parses the response to the `connect` method.
///
/// ## Parameters
///
/// resp: The response slice to parse.
///
/// ## Examples
/// ```
/// use stratum_v1::client_resp::{ConnectResp, parse_response_connect};
///
/// let resp = br#"{"id": 10, "result": null, "error": [20, "Other/Unknown", null]}"#;
/// assert!(parse_response_connect(resp).is_err());
///
/// let resp = br#"{"id": 1, "result": [ [ ["mining.set_difficulty", "b4b6693b72a50c7116db18d6497cac52"], ["mining.notify", "ae6812eb4cd7735a302a8a9dd95cf71f"]], "08000002", 4], "error": null}"#;
/// let r = parse_response_connect(resp).unwrap();
/// assert_eq!(r.subscriptions().len(), 2);
/// assert_eq!(r.extranonce1(), 0x08000002);
/// assert_eq!(r.extranonce2_size(), 4);
///
/// let resp = br#"{"id":2,"error":null,"result":[[["mining.notify","e26e1928"]],"e26e1928",4]}"#;
/// let r = parse_response_connect(resp).unwrap();
/// assert_eq!(r.subscriptions().len(), 1);
/// assert_eq!(r.extranonce1(), 0xe26e1928);
/// assert_eq!(r.extranonce2_size(), 4);
/// ```
pub fn parse_response_connect(resp: &[u8]) -> Result<ConnectResp> {
    serde_json_core::from_slice::<json_rpc_types::Response<ConnectResp, String<64>>>(resp)
        .map_err(Error::msg)?
        .0
        .payload
        .map_err(Error::msg)
}

/// # Parse Response Authorize
///
/// Parses the response to the `authorize` method.
///
/// ## Parameters
///
/// resp: The response slice to parse.
///
/// ## Examples
/// ```
/// use stratum_v1::client_resp::parse_response_authorize;
///
/// let resp = br#"{"id": 10, "result": null, "error": [25, "Not subscribed", null]}"#;
/// assert!(parse_response_authorize(resp).is_err());
///
/// let resp = br#"{"id": 2, "result": true, "error": null}"#;
/// assert_eq!(parse_response_authorize(resp).unwrap(), true);
/// ```
pub fn parse_response_authorize(resp: &[u8]) -> Result<bool> {
    serde_json_core::from_slice::<json_rpc_types::Response<bool, String<64>>>(resp)
        .map_err(Error::msg)?
        .0
        .payload
        .map_err(Error::msg)
}

/// # Parse Response Submit
///
/// Parses the response to the `submit` method.
///
/// ## Parameters
///
/// resp: The response slice to parse.
///
/// ## Examples
/// ```
/// use stratum_v1::client_resp::parse_response_submit;
///
/// let resp = br#"{"id": 10, "result": null, "error": [25, "Not subscribed", null]}"#;
/// assert!(parse_response_submit(resp).is_err());
///
/// let resp = br#"{"id": 2, "result": true, "error": null}"#;
/// assert_eq!(parse_response_submit(resp).unwrap(), true);
/// ```
pub fn parse_response_submit(resp: &[u8]) -> Result<bool> {
    serde_json_core::from_slice::<json_rpc_types::Response<bool, String<64>>>(resp)
        .map_err(Error::msg)?
        .0
        .payload
        .map_err(Error::msg)
}
