# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "foundation-psbt"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin_hashes = { workspace = true }
bitflags = { workspace = true }
either = { workspace = true }
embedded-io = { workspace = true }
foundation-bip32 = { workspace = true }
hex = { workspace = true, features = ["std"] }  # TODO: removeme
nom = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
secp256k1 = { workspace = true }

[dev-dependencies]
foundation-test-vectors = { workspace = true, features = ["psbt"] }

[features]
default = ["std"]
std = ["nom/std"]
