/*
 * SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef FOUNDATION_H
#define FOUNDATION_H

/*
 * Warning: This file is auto-generated by cbindgen, do not edit.
 *
 * Read the Justfile in order to re-generate this file.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#if defined(__clang__)
#define FOUNDATION_NONNULL __attribute__((nonnull))
#else
#define FOUNDATION_NONNULL
#endif

/**
 * Encoded length of a `npub` in bytes.
 */
#define FOUNDATION_NPUB_LEN 63

/**
 * Encoded length of a `nsec` in bytes.
 */
#define FOUNDATION_NSEC_LEN 63

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Encode a public key to a Nostr `npub`.
 */
void foundation_encode_npub(const uint8_t (*FOUNDATION_NONNULL public_key)[32],
                            uint8_t (*FOUNDATION_NONNULL output)[FOUNDATION_NPUB_LEN]);

/**
 * Encode a secret key to a Nostr `nsec`.
 */
void foundation_encode_nsec(const uint8_t (*FOUNDATION_NONNULL secret_key)[32],
                            uint8_t (*FOUNDATION_NONNULL output)[FOUNDATION_NSEC_LEN]);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* FOUNDATION_H */
