# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "foundation-test-vectors"
version = "0.1.0"
authors = ["Foundation Devices, Inc. <hello@foundationdevices.com>"]
description = "Foundation Devices test vectors for various encoding/decoding formats"
license = "GPL-3.0-or-later"
homepage = "https://github.com/Foundation-Devices/foundation-rs"
edition = "2021"

[features]
default = ["std"]
std = ["faster-hex/std", "serde/std"]
bip32 = ["base58ck/std", "faster-hex/serde"]
firmware = []
nostr = ["faster-hex/serde"]
psbt = ["faster-hex/serde"]
seedqr = ["bip39/serde", "faster-hex/serde"]
blockchain-commons = ["bitcoin/serde", "faster-hex/serde"]

[dependencies]
base58ck = { workspace = true, optional = true }
bip39 = { workspace = true, optional = true, features = ["std"] }
bitcoin = { workspace = true, optional = true, features = ["std"] }
faster-hex = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
